name: Publish

on:
  push:

jobs:
  publish_to_devto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish articles on dev.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: 'content/posts/*.md'
          branch: main
          conventional_commits: true
          dry_run: true

  publish_to_medium:
    runs-on: ubuntu-latest
    steps:
      - name: Read the post
        id: post
        run: echo "::set-output name=data::$(cat ./content/post.md)"
      - uses: infraway/medium-post-markdown@v1.5.0
        with:
          access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
          markdown: ${{ steps.post.outputs.data }}

  publish_notification_to_twitter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ethomson/send-tweet-action@v1
        with:
          status: 'Hi, this is a test!'
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
